---
title: "DATA 605 Assignment 1: Vectors & Matrices"
author: "Dan Smilowitz"
date: "August 30, 2016"
output: 
  html_document: 
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, comment = NA)
```


### Problem Set 1

$$u = \left[ \begin{array}{cc}0.5 \\0.5 \end{array} \right]; \ v = \left[ \begin{array}{cc}3 \\-4 \end{array} \right]$$

```{r set-1, echo=FALSE}
u <- c(0.5, 0.5)
v <- c(3, -4)
```


#### Dot Product

Calculate the dot product $u \cdot v$

```{r dot-prod}
(dot_prod <- sum(u * v))
```


#### Length

What are the lengths of $u$ and $v$?

```{r lengths}
(len_u <- sqrt(sum(u * u)))
(len_v <- sqrt(sum(v * v)))
```


#### Linear Combination

What is the linear combination $3u - 2v$?

```{r linear-combination}
3 * u - 2 * v
```


#### Angle

What is the angle between $u$ and $v$?

$$\cos \theta = \frac{u \cdot v}{||u|| \ ||v||}$$

```{r angle}
(theta <- acos(dot_prod / (len_u * len_v)))
```



### Problem Set 2

```{r formula}
elim_solve <- function(A, b) {
  #find pivot
  pivot_1 <- A[1, 1]
  
  #swap if pivot == 0
  if (pivot_1 == 0) {
    A <- A[c(2, 1, 3), ]
    pivot_1 <- A[1, 1]
    if (pivot_1 == 0) {
      A <- A[c(3, 2, 1), ]
      pivot_1 <- A[1, 1]
      }
  }
  #multiplier & eliminate row 2
  mult_2 <- A[2, 1] / pivot_1
  A[2, ] <- A[2, ] - mult_2 * A[1, ]
  b[2] <- b[2] - mult_2 * b[1]
  #multiplier & eliminate row 3
  mult_3 <- A[3, 1] / pivot_1
  A[3, ] <- A[3, ] - mult_3 * A[1, ]
  b[3] <- b[3] - mult_3 * b[1]
  
  #find pivot
  pivot_2 <- A[2, 2]
  
  #swap if pivot == 0
  if (pivot_2 == 0) {
    A <- a[c(1, 3, 2), ]
    pivot_2 <- A[2, 2]
  }
  
  #multiplier & eliminate row 3
  mult_3 <- A[3, 2] / pivot_2
  A[3, ] <- A[3, ] - mult_3 * A[2, ]
  b[3] <- b[3] - mult_3 * b[2]
  
  #solve for x3
  x3 <- b[3] / A[3, 3]
  
  #substitution
  x2 <- (b[2] - A[2, 3] * x3) / A[2, 2]
  x1 <- (b[1] - A[1, 3] * x3 - A[1, 2] * x2) / A[1, 1]
  
  #results
  x <- matrix(c(x1, x2, x3), nrow = 3)
  x
}
```

Test the system
$$\left[ \begin{array}{cc}1 & 1 & 3 \\2 & -1 & 5 \\-1 & -2 & 4 \end{array} \right] \left[ \begin{array}{cc}x_1 \\x_2 \\x_3 \end{array} \right] = \left[ \begin{array}{cc}1 \\2 \\6 \end{array} \right]$$

```{r solve}
eq <- matrix(c(1, 1, 3, 2, -1, 5, -1, -2, 4), nrow = 3, ncol = 3, byrow = TRUE)
constr <- matrix(c(1, 2, 6), nrow = 3)

round(elim_solve(eq, constr), 2)
```
